version: '3'

services:
  
  # ESTOQUE
  
  # Estoque.Api
  
  estoque.api:
    image: estoque.api
    container_name: estoque.api    
    ports:
      - "2001:80"
    build:
      context: ./Estoque.API
      dockerfile: ./Dockerfile
    depends_on:
      - estoque.db
  
  # Estoque.Db

  estoque.db:
    image: postgres
    container_name: estoque.db
    ports:
      - "3001:5432"
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - estoque.db.data:/var/lib/postgresql/data

  # PEDIDOS
  
  # Pedidos.Api
  
  pedidos.api:
    image: pedidos.api
    container_name: pedidos.api
    ports:
      - "2002:80"
    build:
      context: ./Pedidos.API
      dockerfile: ./Dockerfile
    depends_on:
      - pedidos.db
  
  # Pedidos.Db

  pedidos.db:
    image: postgres
    container_name: pedidos.db
    ports:
      - "3002:5432"
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - pedidos.db.data:/var/lib/postgresql/data

volumes:
  estoque.db.data:
  pedidos.db.data: