version: '3.1'

services:
  
  # APIS

  calculadora.api:
    image: taigobrasil/calculadora.api
    ports:
      - "2001:80"

  cep.api:
    image: taigobrasil/calculadora.api
    ports:
      - "2002:80"
    depends_on:
      - cep.db

  # DATABASES

  cep.db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: