version: '3.1'

services:
  
  # APIS

  calculadora.api:
    build:
      context: ./calculadora.api
      dockerfile: ./Dockerfile
    image: taigobrasil/calculadora.api
    container_name: calculadora.api
    ports:
      - "2001:80"

  cep.api:
    build:
      context: ./cep.api
      dockerfile: ./Dockerfile
    image: taigobrasil/cep.api
    container_name: cep.api
    ports:
      - "2002:80"
    depends_on:
      - cep.db

  # DATABASES

  cep.db:
    image: postgres
    container_name: cep.db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: